title: IHDN R Tutorials
description: A collaborative website for IHDN with R programming tutorials
baseurl: "/ihdn"
url: "https://idawiweka.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-sitemap

# Theme settings
remote_theme: jekyll/minima

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:name/
  datasets:
    output: true
    permalink: /datasets/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
      author: "IHDN Team"
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
    values:
      layout: "default"

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: false
    default_lang: r

# Navigation
nav_items:
  - title: Home
    url: /
  - title: Tutorials
    url: /tutorials/
  - title: Datasets
    url: /datasets/
  - title: About
    url: /about/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github 